# Generated by Django 3.0.2 on 2020-02-10 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=128, verbose_name='Nom de la personne')),
                ('phone_number', models.CharField(blank=True, max_length=16, verbose_name='Téléphone')),
                ('email_address', models.CharField(blank=True, max_length=128, verbose_name='Email')),
                ('address_street', models.CharField(blank=True, max_length=128, verbose_name='Adresse')),
                ('address_city', models.CharField(blank=True, max_length=128, verbose_name='Ville')),
                ('address_country', models.CharField(blank=True, max_length=2, verbose_name='Pays')),
                ('private_description', models.TextField(blank=True, verbose_name='Description privée')),
                ('pr_description', models.TextField(blank=True, verbose_name='Description comm')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pro', 'Stand pro'), ('fanzine', 'Stand fanzine/jeune créateur'), ('sponsor', 'Stand sponsor'), ('service_provider', 'Stand prestataire'), ('association', 'Stand association'), ('food', 'Stand nourriture')], max_length=32, verbose_name='Type')),
                ('booth_name', models.CharField(blank=True, max_length=128, verbose_name='Nom du stand')),
                ('price', models.FloatField(verbose_name='Prix')),
                ('price_final', models.BooleanField(default=False, verbose_name='Prix certain ?')),
                ('additional_price_modalities', models.TextField(blank=True, verbose_name='Supplément ?')),
                ('additional_price_sum', models.FloatField(blank=True, null=True, verbose_name='Montant supplément')),
                ('floating', models.TextField(blank=True, verbose_name='Détail flottant ?')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospector.Contact', verbose_name='Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('budget', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LogisticalNeedSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tables', models.IntegerField(default=0)),
                ('chairs', models.IntegerField(default=0)),
                ('panels', models.IntegerField(default=0)),
                ('electrical', models.TextField(blank=True)),
                ('small_plates', models.IntegerField(default=0)),
                ('medium_plates', models.IntegerField(default=0)),
                ('bowls', models.IntegerField(default=0)),
                ('utensils', models.IntegerField(default=0)),
                ('cutlery_comment', models.TextField(blank=True)),
                ('staffs', models.IntegerField(default=0)),
                ('staffs_comment', models.TextField(blank=True)),
                ('other_material', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('useful_views', models.TextField(blank=True)),
                ('typical_next_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prospector.TaskType')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_state', models.CharField(choices=[('5_contact_waits_pro', 'Contact attend sur pro'), ('4_pro_waits_treasury', 'Pro attend sur trésorerie'), ('3_pro_waits_presidence', 'Pro attend sur présidence'), ('2_pro_waits_contact', 'Pro attend sur contact'), ('1_doing', 'Tâche en cours'), ('0_done', 'Tâche terminée')], max_length=32)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospector.Deal')),
                ('taskype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospector.TaskType')),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospector.Event', verbose_name='Événement'),
        ),
        migrations.AddField(
            model_name='deal',
            name='logistical_needs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previsional_deals', to='prospector.LogisticalNeedSet', verbose_name='Besoins logistiques prévisionnels'),
        ),
        migrations.AddField(
            model_name='deal',
            name='tasks',
            field=models.ManyToManyField(through='prospector.Task', to='prospector.TaskType', verbose_name='Tâches'),
        ),
        migrations.CreateModel(
            name='BoothSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('building', models.CharField(max_length=32)),
                ('usual_price', models.FloatField()),
                ('identifier', models.CharField(max_length=256)),
                ('final', models.BooleanField(default=False)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prospector.Deal')),
            ],
        ),
    ]
