# Generated by Django 3.0.2 on 2020-04-01 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0003_auto_20200224_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='budget',
            field=models.FloatField(verbose_name='Budget stands'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='typical_next_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prospector.TaskType', verbose_name='Tâche suivante typique'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='useful_views',
            field=models.TextField(blank=True, help_text='JSON object. Key=Name of button, Value=django URL name', verbose_name='Liens utiles'),
        ),
    ]
