# Generated by Django 3.0.2 on 2020-04-06 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0004_auto_20200401_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email_address',
        ),
        migrations.AddField(
            model_name='deal',
            name='attend_to_mail_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Événement actuel ?'),
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64, unique=True)),
                ('ignore_unlinked', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prospector.Contact')),
            ],
        ),
    ]
