# Generated by Django 3.0.2 on 2020-04-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0006_auto_20200429_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='old_todo_state',
            field=models.CharField(blank=True, choices=[('0_done', 'Tâche terminée'), ('1_doing', 'Tâche en cours'), ('2_pro_waits_contact', 'Pro attend sur contact'), ('3_pro_waits_presidence', 'Pro attend sur présidence'), ('4_pro_waits_treasury', 'Pro attend sur trésorerie'), ('5_contact_waits_pro', 'Contact attend sur pro')], max_length=32, null=True),
        ),
    ]
