# Generated by Django 3.0.2 on 2020-04-29 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospector', '0008_auto_20200429_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comment',
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prospector.TaskComment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospector.Task')),
            ],
        ),
    ]
