# Generated by Django 3.0.2 on 2020-04-30 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0009_auto_20200429_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcomment',
            name='reply_to',
        ),
    ]
