# Generated by Django 3.0 on 2020-05-14 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0010_remove_taskcomment_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boothspace',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='boothspace',
            name='final',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='price_final',
        ),
        migrations.AddField(
            model_name='deal',
            name='additional_price_exists',
            field=models.BooleanField(default=False, verbose_name='Supplément ?'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='additional_price_modalities',
            field=models.TextField(blank=True, verbose_name='Modalités du supplément'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='additional_price_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Montant du supplément'),
        ),
        migrations.CreateModel(
            name='DealBoothSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boothspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospector.BoothSpace')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospector.Deal')),
            ],
        ),
    ]
