# Generated by Django 3.0 on 2020-05-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0011_auto_20200514_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='tags',
            field=models.TextField(blank=True, help_text='JSON list of tag names.', verbose_name='Tags magiques'),
        ),
    ]
