# Generated by Django 3.0 on 2020-05-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0012_tasktype_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='agepoly_president',
            field=models.CharField(default='Delphine Zihlmann', max_length=128, verbose_name='Président AGEPoly'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='polyjapan_president',
            field=models.CharField(default='Roxane Pangaud', max_length=128, verbose_name='Président PolyJapan'),
            preserve_default=False,
        ),
    ]
