# Generated by Django 3.0 on 2020-05-14 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospector', '0013_auto_20200514_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='tags',
            field=models.TextField(blank=True, help_text='Line-separated list of tags', verbose_name='Tags magiques'),
        ),
    ]
