# Generated by Django 3.0 on 2020-05-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0014_auto_20200514_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='wiki_page',
            field=models.URLField(blank=True, max_length=256, verbose_name='Lien wiki'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_country',
            field=models.CharField(blank=True, help_text='Code à deux lettres', max_length=2, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='task',
            name='todo_state',
            field=models.CharField(choices=[('0_done', 'Terminé'), ('1_doing', 'En cours'), ('2_pro_waits_contact', 'Attente contact'), ('3_pro_waits_presidence', 'Attente prés.'), ('4_pro_waits_treasury', 'Attente tréso.'), ('5_contact_waits_pro', 'À faire')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='new_todo_state',
            field=models.CharField(choices=[('0_done', 'Terminé'), ('1_doing', 'En cours'), ('2_pro_waits_contact', 'Attente contact'), ('3_pro_waits_presidence', 'Attente prés.'), ('4_pro_waits_treasury', 'Attente tréso.'), ('5_contact_waits_pro', 'À faire')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='old_todo_state',
            field=models.CharField(blank=True, choices=[('0_done', 'Terminé'), ('1_doing', 'En cours'), ('2_pro_waits_contact', 'Attente contact'), ('3_pro_waits_presidence', 'Attente prés.'), ('4_pro_waits_treasury', 'Attente tréso.'), ('5_contact_waits_pro', 'À faire')], max_length=32, null=True),
        ),
    ]
