# Generated by Django 3.0 on 2020-05-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0016_auto_20200515_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
