# Generated by Django 3.0 on 2020-05-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0017_auto_20200516_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
