# Generated by Django 3.0 on 2020-05-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0018_auto_20200518_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['person_name']},
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['booth_name']},
        ),
        migrations.AddField(
            model_name='tasktype',
            name='default_task_type',
            field=models.BooleanField(default=False, verbose_name='Ce type de tâche est par défaut'),
        ),
    ]
