# Generated by Django 3.0 on 2020-06-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0019_auto_20200518_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fanzine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrees', models.BooleanField(default=False, verbose_name="J'ai lu et je confirme que mon stand correspond aux informations ci-dessus")),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='NOM Prénom')),
                ('address_street', models.CharField(blank=True, max_length=128, verbose_name='Rue / n°')),
                ('address_city', models.CharField(blank=True, max_length=128, verbose_name='Code Postal / Ville')),
                ('address_country', models.CharField(blank=True, help_text='Code à deux lettres', max_length=2, verbose_name='Pays')),
                ('age', models.BooleanField(default=False, verbose_name='Je serai majeur lors de Japan Impact')),
                ('email', models.CharField(blank=True, max_length=128, verbose_name='Adresse e-mail')),
                ('phone_number', models.CharField(blank=True, max_length=16, verbose_name='Numéro de téléphone')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Date (YYYY-MM-JJ)'),
        ),
    ]
