# Generated by Django 3.0 on 2020-07-26 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0019_auto_20200518_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktype',
            name='typical_next_task',
        ),
        migrations.AddField(
            model_name='tasktype',
            name='typical_prev_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typical_next_tasks', to='prospector.TaskType', verbose_name='Type de tâche précédent typique'),
        ),
    ]
