# Generated by Django 3.0 on 2020-06-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0020_auto_20200624_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanzine',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='fanzine',
            name='address_country',
        ),
        migrations.RemoveField(
            model_name='fanzine',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='fanzine',
            name='agrees',
        ),
        migrations.AddField(
            model_name='fanzine',
            name='activities',
            field=models.CharField(default='', max_length=512, verbose_name='Activités supplémentaires'),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='blog_url',
            field=models.CharField(default='', max_length=128, verbose_name='Site/Blog/Autre'),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='deadline',
            field=models.CharField(default='', max_length=128, verbose_name='Date limite pour être prévenu'),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='deco',
            field=models.BooleanField(default=False, verbose_name='Interessé à participer aux atelier déco'),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='deviant_url',
            field=models.CharField(default='', max_length=128, verbose_name='Page DeviantArt'),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='electric_needs',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Besoins électriques importants'),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='facebook_url',
            field=models.CharField(default='', max_length=128, verbose_name='Page Facebook'),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='full_address',
            field=models.CharField(default='', max_length=512, verbose_name='Addresse complète'),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='image_url',
            field=models.CharField(default='', max_length=128, verbose_name="URL d'une image du stand"),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='logistic_needs',
            field=models.CharField(default='', max_length=512, verbose_name='Besoins logistiques'),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='num_people',
            field=models.CharField(default='', max_length=128, verbose_name='Nombre de personnes présentes'),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='prev_editions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='remarks',
            field=models.CharField(default='', max_length=512, verbose_name='Remarques'),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='second_chance',
            field=models.BooleanField(default=False, verbose_name='Si pas choisi mais des places se libèrent, interessé à venir ?'),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='stand_content',
            field=models.CharField(default='', max_length=512, verbose_name='Contenu du stand'),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='stand_description',
            field=models.CharField(default='', max_length=1024, verbose_name='Description du stand'),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='stand_name',
            field=models.CharField(default='', max_length=128, verbose_name='Nom du stand'),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='tables',
            field=models.CharField(default='', max_length=128, verbose_name='Nombre de tables souhaité'),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fanzine',
            name='age',
            field=models.CharField(default='', max_length=128, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='fanzine',
            name='email',
            field=models.CharField(max_length=128, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='fanzine',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='NOM Prénom'),
        ),
        migrations.AlterField(
            model_name='fanzine',
            name='phone_number',
            field=models.CharField(max_length=16, verbose_name='Numéro de téléphone'),
        ),
    ]
