# Generated by Django 3.0 on 2020-08-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0020_auto_20200624_1552_squashed_0023_auto_20200719_1323'),
        ('prospector', '0020_auto_20200726_0023'),
    ]

    operations = [
    ]
