# Generated by Django 3.0 on 2020-07-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0022_auto_20200628_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='FanzineRating',
        ),
        migrations.RemoveField(
            model_name='fanzine',
            name='full_address',
        ),
        migrations.AddField(
            model_name='fanzine',
            name='address_city',
            field=models.CharField(default='', max_length=128, verbose_name='Adresse: Code postal / Ville'),
        ),
        migrations.AddField(
            model_name='fanzine',
            name='address_street',
            field=models.CharField(default='', max_length=128, verbose_name='Adresse: Rue / n°'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='fanzine',
            name='stand_description',
            field=models.TextField(default='', verbose_name='Description du stand'),
        ),
    ]
