# Generated by Django 3.0.2 on 2020-01-23 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=128)),
                ('booth_name', models.CharField(blank=True, max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=16)),
                ('email_address', models.CharField(blank=True, max_length=128)),
                ('address_street', models.CharField(blank=True, max_length=128)),
                ('address_city', models.CharField(blank=True, max_length=128)),
                ('address_country', models.CharField(blank=True, max_length=2)),
                ('private_description', models.TextField(blank=True)),
                ('pr_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pro', 'Professional exhibitor booth'), ('fanzine', 'Fanzine/Young Creator booth'), ('sponsor', 'Sponsor booth'), ('service_provider', 'Service provider booth'), ('association', 'Association booth'), ('food', 'Food booth')], max_length=32)),
                ('price', models.FloatField()),
                ('price_final', models.BooleanField(default=False)),
                ('additional_price_modalities', models.TextField(blank=True)),
                ('additional_price_sum', models.FloatField(blank=True)),
                ('floating', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospector.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LogisticalNeedSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tables', models.IntegerField(default=0)),
                ('chairs', models.IntegerField(default=0)),
                ('panels', models.IntegerField(default=0)),
                ('electrical', models.TextField()),
                ('small_plates', models.IntegerField(default=0)),
                ('medium_plates', models.IntegerField(default=0)),
                ('bowls', models.IntegerField(default=0)),
                ('utensils', models.IntegerField(default=0)),
                ('cutlery_comment', models.TextField()),
                ('staffs', models.IntegerField(default=0)),
                ('staffs_comment', models.TextField()),
                ('other_material', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('useful_views', models.TextField(blank=True)),
                ('typical_next_task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='prospector.Task')),
            ],
        ),
        migrations.CreateModel(
            name='DealTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_state', models.CharField(choices=[('pro_waits_contact', 'Pro waits on contact'), ('pro_waits_treasury', 'Pro waits on treasury'), ('pro_waits_presidence', 'Pro waits on presidence'), ('contact_waits_pro', 'Contact waits on pro'), ('done', 'This task is done')], max_length=32)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospector.Deal')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospector.Task')),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospector.Event'),
        ),
        migrations.AddField(
            model_name='deal',
            name='logistical_needs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospector.LogisticalNeedSet'),
        ),
        migrations.AddField(
            model_name='deal',
            name='tasks',
            field=models.ManyToManyField(through='prospector.DealTask', to='prospector.Task'),
        ),
        migrations.CreateModel(
            name='BoothSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('identifier', models.CharField(max_length=256)),
                ('final', models.BooleanField(default=False)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospector.Deal')),
            ],
        ),
    ]
