# Generated by Django 3.0.2 on 2020-01-23 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticalneedset',
            name='cutlery_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='logisticalneedset',
            name='electrical',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='logisticalneedset',
            name='other_material',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='logisticalneedset',
            name='staffs_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='typical_next_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prospector.Task'),
        ),
    ]
