# Generated by Django 3.0.2 on 2020-02-10 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskype',
            new_name='tasktype',
        ),
    ]
