# Generated by Django 3.0.2 on 2020-01-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0002_auto_20200123_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boothspace',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prospector.Deal'),
        ),
    ]
