# Generated by Django 3.0.2 on 2020-01-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0003_auto_20200128_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='boothspace',
            name='building',
            field=models.CharField(default='CE', max_length=32),
            preserve_default=False,
        ),
    ]
