# Generated by Django 3.0.2 on 2020-01-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0004_boothspace_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='budget',
            field=models.FloatField(default=4000),
            preserve_default=False,
        ),
    ]
