# Generated by Django 3.0.2 on 2020-01-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0005_event_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='boothspace',
            name='usual_price',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
