# Generated by Django 3.0.2 on 2020-02-07 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0006_boothspace_usual_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='logistical_needs',
        ),
        migrations.AddField(
            model_name='deal',
            name='actual_logistical_needs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prospector.LogisticalNeedSet', verbose_name='Besoins logistiques finaux'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_city',
            field=models.CharField(blank=True, max_length=128, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_country',
            field=models.CharField(blank=True, max_length=2, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_street',
            field=models.CharField(blank=True, max_length=128, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='booth_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nom du stand'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.CharField(blank=True, max_length=128, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='person_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nom de la personne'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='pr_description',
            field=models.TextField(blank=True, verbose_name='Description comm'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='private_description',
            field=models.TextField(blank=True, verbose_name='Description privée'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='additional_price_modalities',
            field=models.TextField(blank=True, verbose_name='Supplément ?'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='additional_price_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Montant supplément'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospector.Contact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospector.Event', verbose_name='Événement'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='floating',
            field=models.TextField(blank=True, verbose_name='Détail flottant ?'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='price',
            field=models.FloatField(verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='price_final',
            field=models.BooleanField(default=False, verbose_name='Prix certain ?'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='tasks',
            field=models.ManyToManyField(through='prospector.DealTask', to='prospector.Task', verbose_name='Tâches'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='type',
            field=models.CharField(choices=[('pro', 'Stand pro'), ('fanzine', 'Stand fanzine/jeune créateur'), ('sponsor', 'Stand sponsor'), ('service_provider', 'Stand prestataire'), ('association', 'Stand association'), ('food', 'Stand nourriture')], max_length=32, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='dealtask',
            name='todo_state',
            field=models.CharField(choices=[('pro_waits_contact', 'Pro attend sur contact'), ('pro_waits_treasury', 'Pro attend sur trésorerie'), ('pro_waits_presidence', 'Pro attend sur présidence'), ('contact_waits_pro', 'Contact attend sur pro'), ('doing', 'Tâche en cours'), ('done', 'Tâche terminée')], max_length=32),
        ),
    ]
