# Generated by Django 3.0.2 on 2020-02-07 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0008_auto_20200207_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='provisional_logistical_needs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previsional_deals', to='prospector.LogisticalNeedSet', verbose_name='Besoins logistiques prévisionnels'),
        ),
    ]
