# Generated by Django 3.0.2 on 2020-02-07 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0010_auto_20200207_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='actual_logistical_needs',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='provisional_logistical_needs',
        ),
        migrations.AddField(
            model_name='deal',
            name='logistical_needs',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='previsional_deals', to='prospector.LogisticalNeedSet', verbose_name='Besoins logistiques prévisionnels'),
            preserve_default=False,
        ),
    ]
