# Generated by Django 3.0.2 on 2020-02-08 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0011_auto_20200207_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='logistical_needs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previsional_deals', to='prospector.LogisticalNeedSet', verbose_name='Besoins logistiques prévisionnels'),
        ),
        migrations.AlterField(
            model_name='dealtask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
