# Generated by Django 3.0.2 on 2020-02-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospector', '0012_auto_20200208_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealtask',
            name='todo_state',
            field=models.CharField(choices=[('5_contact_waits_pro', 'Contact attend sur pro'), ('4_pro_waits_treasury', 'Pro attend sur trésorerie'), ('3_pro_waits_presidence', 'Pro attend sur présidence'), ('2_pro_waits_contact', 'Pro attend sur contact'), ('1_doing', 'Tâche en cours'), ('0_done', 'Tâche terminée')], max_length=32),
        ),
    ]
